# HYPOTHESIS TESTING ASSIGNMENT

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats
import scipy as sp
import statsmodels.api as sm
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt
from statsmodels.stats.proportion import proportions_ztest


# Question 1



A F&B manager wants to determine whether there is any significant difference in the diameter of the cutlet between two units. 
A randomly selected sample of cutlets was collected from both units and measured? 
Analyze the data and draw inferences at 5% significance level. 
Please state the assumptions and tests that you carried out to check validity of the assumptions.


Minitab File : Cutlets.mtw


#H0: mu=mu2
#H1: mu1!=mu2

In [2]:
# load the dataset
cutlets = pd.read_csv("Cutlets.csv")

In [3]:
cutlets.head(10)

Unit A  Unit B
0  6.8090  6.7703
1  6.4376  7.5093
2  6.9157  6.7300
3  7.3012  6.7878
4  7.4488  7.1522
5  7.3871  6.8110
6  6.8755  7.2212
7  7.0621  6.6606
8  6.6840  7.2402
9  6.8236  7.0503

In [4]:
cutlets.describe()

Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [8]:
unita=cutlets['Unit A']

In [9]:
unitb=cutlets['Unit B']

In [10]:
stats.ttest_ind(unita,unitb)

Ttest_indResult(statistic=0.7228688704678063, pvalue=0.4722394724599501)

###pvalue>0.05 then accept null hypothesis

# Question 2


A hospital wants to determine whether there is any difference in the average Turn Around Time (TAT) of reports of the laboratories on their preferred list. 
They collected a random sample and recorded TAT for reports of 4 laboratories. 
TAT is defined as sample collected to report dispatch.
   
Analyze the data and determine whether there is any difference in average TAT among the different laboratories at
5% significance level.
 
 
    Minitab File: LabTAT.mtw


In [11]:
# load the dataset
labtat = pd.read_csv("LabTAT.csv")

In [12]:
labtat.head()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
0        185.35        165.53        176.70        166.13
1        170.49        185.91        198.45        160.79
2        192.77        194.92        201.23        185.18
3        177.33        183.00        199.61        176.42
4        193.41        169.57        204.63        152.60

In [18]:
labtat.describe()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [13]:
# Anova ftest statistics: stats.f_oneway(column-1,column-2,column-3,column-4)
p_value=stats.f_oneway(labtat.iloc[:,0],labtat.iloc[:,1],labtat.iloc[:,2],labtat.iloc[:,3])
p_value

F_onewayResult(statistic=118.70421654401437, pvalue=2.1156708949992414e-57)

In [14]:
p_value[1]  # compare it with α = 0.05

2.1156708949992414e-57

# Question 3


Sales of products in four different regions is tabulated for males and females. Find if male-female buyer rations are similar across regions.



In [15]:
# load the dataset
buyer = pd.read_csv("BuyerRatio.csv")
buyer


Observed Values  East  West  North  South
0           Males    50   142    131     70
1         Females   435  1523   1356    750

In [16]:
Male = pd.Series(buyer.iloc[0,:])
Male

Observed Values    Males
East                  50
West                 142
North                131
South                 70
Name: 0, dtype: object

In [37]:
Female = pd.Series(buyer.iloc[1,:])
Female

Observed Values    Females
East                   435
West                  1523
North                 1356
South                  750
Name: 1, dtype: object

In [17]:
# Make dimensional array
obs=np.array([[50,142,131,70],[435,1523,1356,750]])
obs

array([[  50,  142,  131,   70],
       [ 435, 1523, 1356,  750]])

In [18]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [44]:
stat, p, dof, exp = stats.chi2_contingency(table) 
print(stat,"\n", p,"\n", dof,"\n", exp)

1.595945538661058 
 0.6603094907091882 
 3 
 [[  42.76531299  146.81287862  131.11756787   72.30424052]
 [ 442.23468701 1518.18712138 1355.88243213  747.69575948]]


In [19]:
# Chi2 contengency independence test
chi2_contingency(obs) # o/p is (Chi2 stats value, p_value, df, expected obsvations)

(1.595945538661058,
 0.6603094907091882,
 3,
 array([[  42.76531299,  146.81287862,  131.11756787,   72.30424052],
        [ 442.23468701, 1518.18712138, 1355.88243213,  747.69575948]]))

#Compare p_value with α = 0.05

#pvalue>0.05 then accept null hypothesis

# Question 4


TeleCall uses 4 centers around the globe to process customer order forms. 
They audit a certain %  of the customer order forms. 
Any error in order form renders it defective and has to be reworked before processing.
The manager wants to check whether the defective %  varies by centre. 
Please analyze the data at 5% significance level and help the manager draw appropriate inferences

Minitab File: CustomerOrderForm.mtw

    

In [23]:
#load the dataset
data = pd.read_csv('Costomer+OrderForm.csv')
data

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [24]:
data.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [25]:
data.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [26]:
data.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [27]:
data.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [28]:
# Make a contingency table
obs=np.array([[271,267,269,280],[29,33,31,20]])
obs

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [29]:
# Chi2 contengency independence test
chi2_contingency(obs) # o/p is (Chi2 stats value, p_value, df, expected obsvations)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

#Compare p_value with α = 0.05

##pvalue<0.05 then reject alternative hypothesis